name: Lint Code

on:
  push:
    branches: [main]
  pull_request:

jobs:
  solidity:
    name: Lint Solidity Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: lint commit msg
        run: pnpm lint:sol
